version: "3.2"
services:
  build_system:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: build_system
    image: build_system_image
    env_file:
      - ./.env
    networks:
      - build_system_nw

  build_system_test:
    image: build_system_image
    container_name: build_system_test
    depends_on:
      - build_system
      - nginx
    entrypoint: >
      sh -c "pytest ./tests -o log_cli=true -v --log-level=DEBUG --disable-warnings"
    networks:
      - build_system_nw

  nginx:
    container_name: nginx
    image: nginx:1.20.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - "8081:8081"
    depends_on:
      - build_system
    networks:
      - build_system_nw
    restart: always

networks:
  build_system_nw:
    driver: bridge
